#!/bin/sh

flist=$1
start=$2
end=$3

# for testing
# flist=./list/test.list
# start=1
# end=5

outputDir=./rootfiles/tmp_root

logDir=./log/loop

for count in $(seq $start $end)
  do
  input=`head -${count} ${flist} | tail -1`
  echo ${input}
  filename=`basename ${input}`
  filename="${filename%.*}"
  echo ${filename}
  
  log=${logDir}/${filename}.ss.log
  
  rootout=${outputDir}/${filename}.ss.tmp.root

  root -l -q run_process.cc\(\"ss\",\"${input}\",\"${rootout}\"\) > $log 2>&1

  echo "$count event finished"
  
done


# root -l -q run_process.cc\(\"ss\",\"/group/ilc/users/yokugawa/QQbar250/l5/eLpR/15162/dEdx_corr/QQbarProcessor_out/rv02-02.sv02-02.mILD_l5_o1_v02.E250-SetA.I500010.P2f_z_h.eL.pR.n002.d_dstm_15162_000.root\",\"rootfiles/tmp_root/rv02-02.sv02-02.mILD_l5_o1_v02.E250-SetA.I500010.P2f_z_h.eL.pR.n002.d_dstm_15162_000.ss.tmp.root\"\)
